### ISSUE TITLE
Ability to pin people to the startscreen

### ISSUE THREAD

**Issue by Tourniquet88** [MahStudio/Winsta#12]
As i mentioned weeks ago in the chatroom already, it would be awesome if it was possible to pin any people (even if you don't follow them) to the start screen and see the latest pic in the tile.

**Comment by NGame1** [comment]
Starting from now we are working on the pinning people (UserAccounts) to start screen.
In the first release, it will be a shortcut to the profile only but maybe we will add Notifications about new stories, Highlights and posts on the live tile too.
Keep eye on our updates here and thank you for being a part of MahStudios insider program.

**Comment by NGame1** [comment]
Pinning people feature to the start screen added to build 1.2.29.0 and coming next week.
