### ISSUE TITLE
the number of comments don't change instanty

### ISSUE THREAD

**Issue by hoseinzamani** [MahStudio/Winsta#16]
When I add a comment on a post, Comments number don't change instantly, and it doesn't show my comment below the post before refreshing manually.
I've just added a comment on a post and when I tap on "see all 0 comments" , it shows my recently added comment.

**Comment by NGame1** [comment]
Hi and thanks for being a part of Winsta app development.
This issue fixed when you add a comment using Quick commenting feature.
Regards
