### ISSUE TITLE
Set custom save location [and more]

### ISSUE THREAD

**Issue by Tourniquet88** [MahStudio/Winsta#19]
Right now images and stuff get saved under 'Downloads'. The problem with though is, 'Downloads' is not part of the Photos App, so you won't have those images show up there at all.

It would be nice to have those settings:

Set custom location for images.
Set custom location for videos.

Also it would be much cleaner if Winsta wouldn't create sooo many folders. 

A better way would be this:

Photos\Winsta\%username%\%username%_yyMMddHHmmss

This way you have all images / videos from the same person in the same folder.

**Comment by NGame1** [comment]
The new way of saving media is coming to the next update.
In the next update, Media will be saved in to the pictures library.
