### ISSUE TITLE
Live Tile #FeatureRequest

### ISSUE THREAD

**Issue by KARAKI93** [MahStudio/Winsta#20]
Since this is a social media app I prefer that the main live tile isn't used only for notification but also to show the top 5 post like the 9gag app I use does 
it makes the tile somehow like android widgets and makes it useful
and of course this feature can be turned off

![image](https://user-images.githubusercontent.com/29580929/50055858-ec9f6980-015c-11e9-816e-001f8f05f9fe.png)

**Comment by Tourniquet88** [comment]
Maybe with 

a) an option to turn the live tile on / off. I can see that some people might prefer a more static version to know "ah thats winsta".

b) an optional chaseable live tile, so if you see a nice post, you'll end there right away.

**Comment by KARAKI93** [comment]
@Tourniquet88 That's exactly what I'm talking about

**Comment by NGame1** [comment]
Live tile is now a part of V2.9.2.0 an greater versions. 
You can turn on or off Live tile and also direct notifications from Settings -> Winsta Settings.
