### ISSUE TITLE
Error When clicking on old shared story in directs

### ISSUE THREAD

**Issue by lorisobi** [MahStudio/Winsta#28]
![5dd9a06a-d20f-4f69-9be0-860b7afef53f](https://user-images.githubusercontent.com/28399150/51783291-30ac6380-2138-11e9-9ae0-be179fb2f398.jpg)

Error when clicking on old shared story in directs.

Arg_ArgumentOutOfRangeException

HP
HP Spectre x360 Convertible 15-ch0xx
WINDOWS

**Comment by NGame1** [comment]
This issue is fixed. 
But there's a known issue that if user having a new posted story app will show the new stories ! 
We are working to fix it too but it's not critical.
