### ISSUE TITLE
Composing a post or a story result in a blank window on PC

### ISSUE THREAD

**Issue by shmykelsa** [MahStudio/Winsta#38]
Start composing a post from the PC will result in an empty blank space no matter if the folder is full of photos. I can wait forever, but no photo will be loaded. Same applies for stories. 

Version is 1.2.86.0

**Comment by shmykelsa** [comment]
This issue persists on version 1.2.90.0

**Comment by NGame1** [comment]
@shmykelsa Could you please post a screenshot of photos in folder and winsta photo picker UI ?

**Comment by shmykelsa** [comment]
Sure, here's a quick example:

![image](https://user-images.githubusercontent.com/9965637/53508441-098bdd80-3aba-11e9-89dc-f64113466fbf.png)
![image](https://user-images.githubusercontent.com/9965637/53508493-27594280-3aba-11e9-973f-2afa5debee3f.png)
![image](https://user-images.githubusercontent.com/9965637/53508563-448e1100-3aba-11e9-99b7-1afade0fb9b8.png)
![image](https://user-images.githubusercontent.com/9965637/53508600-52439680-3aba-11e9-8efe-7882df1b42b2.png)

**Comment by shmykelsa** [comment]
This issue persists with 1.3.1.0

**Comment by shmykelsa** [comment]
Solved with 1.4.0.0
