### ISSUE TITLE
Double tap on a photo is way too difficult on Lumia 650

### ISSUE THREAD

**Issue by shmykelsa** [MahStudio/Winsta#44]
Trying to double tap a post to leave a like will not be successful 8 times out of 10. If I tap too calmly or too quickly, the photo will just open fullscreen, leaving it almost impossible to browse and double tap to leave a like.

**Comment by MarcAnt01** [comment]
Sometimes I have the same issue on my PC, even if 2/3 of times it's OK, I would suggest to remove the possibility to open a photo in full screen mode, because of that and being useless,  and leave it as in Instagram official client

**Comment by KARAKI93** [comment]
@MarcAnt01 A simple fix would be to adopt the 6tin way which is dividing the picture in to and pressing on each side will achieve something

**Comment by MarcAnt01** [comment]
I have no idea, I think removing the possibility of full screen photos, would be good anyway and may fix it, as there are no advantages of watching it full screen, apart from pressing back button one more time.

**Comment by shmykelsa** [comment]
This issue has beens solved from the latest 2 or 3 betas. I'll close it.

**Comment by shmykelsa** [comment]
I'm having difficulties again.

**Comment by NGame1** [comment]
It should be fixed in current versions but if you still having problem just report.
