### ISSUE TITLE
Occasionally posts in feed have weird and bigger text then other parts

### ISSUE THREAD

**Issue by shmykelsa** [MahStudio/Winsta#55]
![image](https://user-images.githubusercontent.com/9965637/54424801-a5008d80-470b-11e9-80f3-b0d89ae52352.png)

This is a quick example

**Comment by shmykelsa** [comment]
![image](https://user-images.githubusercontent.com/9965637/55667465-02947f80-585d-11e9-9286-0c2cc81fa7bb.png)

Just had another one today

**Comment by NGame1** [comment]
This issue has been solved in about 95% of captions. normally you will not be going to see such captions anymore.
