### ISSUE TITLE
White hamburger menu in battery saver mode

### ISSUE THREAD

**Issue by Tourniquet88** [MahStudio/Winsta#59]
When I enabled dark mode and the battery saver mode is turned on, the hamburger menu background is turned whiteish. It's very hard to read the menu that way and makes it a very jarring experience overall. As long as dark mode is selected, it should be consistent even with battery saver mode turned on.

**Comment by NGame1** [comment]
It happens on Build 14393 and on higher builds when you disable transparency effects or you turn battery saver on. 
This issue has been fixed
