### ISSUE TITLE
Error when clicking on navviewitems while watching a recorded IG-livestream

### ISSUE THREAD

**Issue by lorisobi** [MahStudio/Winsta#61]
Arg_NullReferenceException

HP
HP Spectre x360 Convertible 15-ch0xx
WINDOWS

SPECTRE
3DM20EA#ABD

**Comment by NGame1** [comment]
@lorisobi Is it possible to explain more? I didn't get what you mean at all

**Comment by NGame1** [comment]
No more explain received. 
Feel free to re-open if you still have this issue and can provide us more details
