### ISSUE TITLE
Error when going to post

### ISSUE THREAD

**Issue by paulies-crown** [MahStudio/Winsta#81]
I hit the "Feed" or "Story" button and it brings up this error:

Unspecified error (Excep_FromHResult 0x80004005)
Acer
Nitro AN515-53
WINDOWS
LAPTOP-0P48AHH1
0000000000000000

**Comment by NGame1** [comment]
Hi there, 
Did you disable the Windows Search Service? 
And isn't our latest updates helped you with this issue?

**Comment by paulies-crown** [comment]
Oh, I didn't know you had to disable that. Now it works, but when I go to post and select a folder, it doesn't show any pictures or anything

**Comment by NGame1** [comment]
Do you have pictures in your Windows Pictures Library folder?

**Comment by paulies-crown** [comment]
are PNG and png different?

**Comment by NGame1** [comment]
No. even pNg pnG or anything else.

**Comment by paulies-crown** [comment]
because I have png files and they aren't showing up

**Comment by NGame1** [comment]
This error should be fixed in our latest updates. 
Please re-open if you still have this issue.
