### ISSUE TITLE
Exception when going into Directs

### ISSUE THREAD

**Issue by thjwong** [MahStudio/Winsta#82]
I recently purchased Winsta for my Windows 10 PC and especially for my Windows Phone 10

The Winstapp works except for one very important function - Directs
Whenever I click onto Directs (the paper plane icon) on my Phone or on my PC Winsta app, it stops working with Exception:

*** *** ***
Invalid Pointer

Arg_NullReferenceException

*** *** ***

For your information, there is not content in the Directs of this instagram account yet.

Please take a look at this bug.

**Comment by NGame1** [comment]
Hi there,
```For your information, there is not content in the Directs of this instagram account yet.```
You mean you didn't receive any direct message till now, right?
ok I will check it

**Comment by NGame1** [comment]
Thanks for reporting.
This issue has been addressed and it will be solved on next update.
Thanks for being a part of Winsta development.
