### ISSUE TITLE
Scroll set of photos in a post with Shift+Scroll

### ISSUE THREAD

**Issue by xperiandri** [MahStudio/Winsta#84]
When you scroll a feed with mouse and then a post with a set of photos appear scroll switches to FlipView photos scrolling. It would be nice to switch this behavior to Shift+Scroll for FlipView

**Comment by xperiandri** [comment]
Ah, there is already a similar issue #76

**Comment by NGame1** [comment]
I don't know exactly if I can change this behaviour or no.

**Comment by NGame1** [comment]
Closed -> Same issue. #76
