### ISSUE TITLE
Arg_ArgumentException

### ISSUE THREAD

**Issue by GusanoGris** [MahStudio/Winsta#86]
Arg_ArgumentException

System manufacturer
System Product Name
WINDOWS

XXXXXXXXXXXXXX
SKU

**Comment by NGame1** [comment]
When and Where ?
If you get it in Explore, It solved by our latest update today. Please update your app to the latest version.

**Comment by GusanoGris** [comment]
Aparece el mismo error en ambas opciones

> The same error appears in both options

![Winstap 02](https://user-images.githubusercontent.com/52173571/60096631-bc5f0600-9751-11e9-8e29-40e6241ab4f7.JPG)

**Comment by NGame1** [comment]
It must be fixed if you still having problem notify me.
