### ISSUE TITLE
Retraso en la carga

### ISSUE THREAD

**Issue by GusanoGris** [MahStudio/Winsta#87]
Han pasado mas de 10 minutos intentando cargar y nada

Traslate:
> It's been more than 10 minutes trying to load and nothing

![Winstap 01](https://user-images.githubusercontent.com/52173571/60096255-c6ccd000-9750-11e9-87da-3f4c645ad2e4.JPG)

**Comment by NGame1** [comment]
It should be related to the version that was patched by Instagram. In our latest updates you shouldn't have any problem.
