### ISSUE TITLE
Search > Recent

### ISSUE THREAD

**Issue by marattmohith** [MahStudio/Winsta#88]
The Search>Recent section is broken.
![image](https://user-images.githubusercontent.com/9216766/62408161-da861480-b5e1-11e9-8fc5-71ce2e32248d.png)

**Comment by marattmohith** [comment]
And Search>Type someone>Enter Profile>Click on Photo>Click again for full screen photo>Press Esc to close the photo full screen mode>But you go back to the Search screen.

**Comment by NGame1** [comment]
Hi there, What version of the app do you have? 
Please install v1.8.116.0 build or later as it released. I don't have this issue on the current version I am working on it by myself.

**Comment by NGame1** [comment]
> And Search>Type someone>Enter Profile>Click on Photo>Click again for full screen photo>Press Esc to close the photo full screen mode>But you go back to the Search screen.

About this issue, Yes it's right I will fix it. have to find some solution for it
