### ISSUE TITLE
New stories fail to be posted

### ISSUE THREAD

**Issue by ajmcc** [MahStudio/Winsta#92]
I tried both desktop and mobile, current version of app from Store as of 2-12-2019.
After a brief pause, the app reports 'Story uploaded' or somesuch, but the story does not appear in my 'feed' (or whatever they call it, I've not used Instagram before).
Clearly the app is essentially useless unless this is fixed.

**Comment by NGame1** [comment]
Hi there, 
When you see Story uploaded successfully it means your story sent without any problems. 
Once you refresh your feeds you can see your posted story.

**Comment by ajmcc** [comment]
Thanks for the reply, however I'm not seeing the post. My total posts counter still reads '0', and when I click on my account name at the top left, the main part of the page is empty. Seems like my post never made it to the Instagram server.

**Comment by NGame1** [comment]
Stories are different than posts. 
If you want to post something after clicking on + button then click on Feed, not stories.
