### ISSUE TITLE
Voice message Play/Pause feature

### ISSUE THREAD

**Issue by zioDorico** [MahStudio/Winsta#97]
When I listen an audio on direct and pause it after few seconds, it will start if I click the label to type some text. This problem aren't exist when I listen the whole audio message.
Thanks for this awesome app. I hope that you'll continue to develop that. Thanks

**Comment by NGame1** [comment]
Currently, Winsta doesn't support pausing voice messages.
every time you tap on play button it plays from the beginning but I will see if I can pause.

**Comment by NGame1** [comment]
Fix will be available in Winsta 3.0
