### ISSUE TITLE
winsta not uploading

### ISSUE THREAD

**Issue by honeyworship** [MahStudio/Winsta#99]
I downloaded and then paid for the Winsta app on my Surface Go and it worked fine for a while, but for the past few days when I try to upload an image, I get this error message.

Arg_NullReferenceException

Arg_NullReferenceException
   at UnofficialInstagram!<BaseAddress>+0x19a0c62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x65496e
   at SharedLibrary!<BaseAddress>+0x4f50d8
   at SharedLibrary!<BaseAddress>+0x4f543c
   at SharedLibrary!<BaseAddress>+0x4a0ad0
   at UnofficialInstagram!<BaseAddress>+0x13a9698
   at UnofficialInstagram!<BaseAddress>+0x13a95d4
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs eventArgs)
   at System.EventHandler<System.Threading.Tasks.UnobservedTaskExceptionEventArgs>.Invoke(Object sender, Threading.Tasks.UnobservedTaskExceptionEventArgs e)
   at UnofficialInstagram!<BaseAddress>+0x14fb996
   at UnofficialInstagram!<BaseAddress>+0x14fc14f
<unknown>
Microsoft Corporation
Surface Go
WINDOWS

DESKTOP-IB0PBRG
Surface_Go_1824_Consumer

and its driving me crazy. please please help me figure out how to fix this.

**Comment by SirHaziel** [comment]
Few days like this already, I've sent couple error messages as well.
Happened just after the Stay Home thing.

**Comment by NGame1** [comment]
We pushed an update yesterday. 
You should be able to upload anything on XBOX, Mobile, and PC in the latest update.
Try and notify me if it didn't work.

**Comment by GMHaziel** [comment]
It is now displaying an error of the image not being in the right format.
Won't upload again even images it has uploaded normally before the bug.

For the record, I'm trying to upload a normal 1000x1000 png image.
Attached file:
![SANDSTORMSET](https://user-images.githubusercontent.com/62876138/78214736-5182ee00-748c-11ea-9fb0-8d9af31a3025.png)

**Comment by NGame1** [comment]
> It is now displaying an error of the image not being in the right format.
> Won't upload again even images it has uploaded normally before the bug.
> 
> For the record, I'm trying to upload a normal 1000x1000 png image.
> Attached file:
> ![SANDSTORMSET](https://user-images.githubusercontent.com/62876138/78214736-5182ee00-748c-11ea-9fb0-8d9af31a3025.png)

I fixed it in V2.9.2.0 and higher versions. 
https://instagram.com/p/B_us5aqplk3
Wait for the fix soon.
